AdaRestaurants/Models/Brand.cs
namespace AdaRestaurants.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Brand")]
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            Foods = new HashSet<Food>();
        }

        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string BrandName { get; set; }

        [StringLength(500)]
        public string BrandDesc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
    }
}

AdaRestaurants/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdaRestaurants.Models;

namespace AdaRestaurants.Controllers
{
    public class BrandController : Controller
    {
        private ModelContext db = new ModelContext();

        // GET: Brand
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: Brand/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brand/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,BrandName,BrandDesc")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: Brand/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brand/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BrandName,BrandDesc")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: Brand/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdaRestaurants/Controllers/SiteHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdaRestaurants.App_Classes;
using AdaRestaurants.Models;

namespace AdaRestaurants.Controllers
{
    public class SiteHomeController : Controller
    {
        // GET: SiteHome
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Bucket()
        {
            return PartialView();
        }
        public PartialViewResult Slider()
        {
            return PartialView();
        }
        public PartialViewResult NewFoods()
        {

            var data = Context.Connect.Foods.ToList();
            return PartialView(data);
        }
        public PartialViewResult Services()
        {
            return PartialView();
        }
        public PartialViewResult Sales()
        {
            return PartialView();
        }
        public PartialViewResult Brands()
        {
            var data = Context.Connect.Brands.ToList();
            return PartialView(data);
        }
        public void AddToBucket(int id)
        {
            BucketItem bi = new BucketItem();
            Food f = Context.Connect.Foods.FirstOrDefault(x => x.ID == id);
            bi.Food = f;
            bi.Quantity = 1;
            bi.Sale = 0;
            Bucket b = new Bucket();
            b.AddBucket(bi);


            
        }

        public PartialViewResult MiniBucketWidget()
        {
            if (HttpContext.Session["ActiveBucket"] != null)
                return PartialView((Bucket)HttpContext.Session["ActiveBucket"]);
            else return PartialView();
        }

        public void BucketFoodRemove(int id)
        {
            if (HttpContext.Session["Activebucket"] != null)
            {
                Bucket b = (Bucket)HttpContext.Session["ActiveBucket"];
                if (b.Foods.FirstOrDefault(x => x.Food.ID == id).Quantity > 1)
                {
                    b.Foods.FirstOrDefault(x => x.Food.ID == id).Quantity--;
                }
                    
                else
                {
                    BucketItem bi = b.Foods.FirstOrDefault(x => x.Food.ID == id);
                    b.Foods.Remove(bi);
                }
            }
        }

        public ActionResult FoodDetail(string id)
        {
            Food f = Context.Connect.Foods.FirstOrDefault(x => x.FoodName == id);
            return View(f);
        }

        public ActionResult FoodRestaurant(int id)
        {
            var data = Context.Connect.Foods.Where(x => x.BrandID == id).ToList();
            return View(data);

        }
    }
}

AdaRestaurants/Views/SiteHome/Brands.cshtml
@model IEnumerable<AdaRestaurants.Models.Brand>
<div class="box">
    <div class="container">
        <div class="tesla-carousel" data-tesla-plugin="carousel" data-tesla-container=".tesla-carousel-items" data-tesla-item=">div" data-tesla-autoplay="false" data-tesla-rotate="false">
            <div class="site-title">
                <ul class="wrapper-arrows">
                    <li><i class="icon-517 prev" title="left arrow"></i></li>
                    <li><i class="icon-501 next" title="right arrow"></i></li>
                </ul>
                <div class="site-inside"><span>Restoranlarımız</span></div>
            </div>
            <div class="row">
                <div class="tesla-carousel-items">
                    @foreach (var brd in Model)
                    {
                        <div class="col-md-3 col-xs-6">
                            <div class="product">
                                <div class="product-cover">
                                    <span class="product-action">

                                    </span>
                                    <div class="product-cover-hover"><span><a href="/SiteHome/FoodRestaurant/@brd.ID">Bax</a></span></div>
                                   
                                        <img src="/Images/@(brd.BrandName+".jpg")    " alt="product name" />
                                    

                                </div>
                                <div class="product-details">
                                    <h1>
                                        <a href="/SiteHome/FoodRestaurant/@brd.ID">
                                            @brd.BrandName
                                    </a>
                                </h1>
                                <p></p>
                               
                            </div>
                        </div>
                    </div>
                    }


                </div>
            </div>
        </div>
    </div>
</div>

AdaRestaurants/Views/SiteHome/Bucket.cshtml

<div class="cart-all">
    <i class="icon-19" title="19"></i>$ (234)
    <div class="inside-cart">
        <p>2 products in the shopping bag</p>
        <ul>
            <li>
                <div class="inside-cart-image"><img src="images/photos/image-9.jpg" alt="product name" /></div>
                <button>x</button>
                <a href="product.html">Stripe boucle</a>
                <p>Unit price 50$</p>
                <p>Q-ty: 1</p>
            </li>
            <li>
                <div class="inside-cart-image"><img src="images/photos/image-8.jpg" alt="product name" /></div>
                <button>x</button>
                <a href="product.html">Stripe boucle</a>
                <p>Unit price 75$</p>
                <p>Q-ty: 2</p>
            </li>
        </ul>
    </div>
</div>

AdaRestaurants/Views/SiteHome/FoodDetail.cshtml
@model AdaRestaurants.Models.Food
@{
    ViewBag.Title = Model.FoodName + "FoodDetail";
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}

<script>
    $(document).ready(function myfunction() {
        $(".addtobucket").click(function myfunction() {
            var id = $(this).attr("name");

            $.ajax({
                type: "GET",
                url: "/SiteHome/AddToBucket",
                data: { id: id },
                success: function myfunction() {
                    $.ajax({
                        type: "GET",
                        url: "/SiteHome/MiniBucketWidget",

                        success: function Verigetir(veri) {
                            $(".cart-all").html('');
                            $(".cart-all").html(veri);
                        }

                    });




                },
                error: function myfunction() {
                    alert("Seçdiyiniz yemək səbətə əlavə olunmadı");
                }
            });
        });
        });
</script>

<div class="product-one">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="the-slider product-big-image" data-tesla-plugin="slider" data-tesla-item=".slide" data-tesla-next=".product-image-arrows-right" data-tesla-prev=".product-image-arrows-left" data-tesla-container=".slide-wrapper">
                    <ul class="product-image-arrows">
                        <li class="product-image-arrows-left"><i class="icon-517" title="left"></i></li>
                        <li class="product-image-arrows-right"><i class="icon-501" title="right"></i></li>
                    </ul>
                    <ul class="slide-wrapper">
                        @foreach (var item in Model.Images)
                        {
                        <li class="slide"><img src="/images/@item.Name" alt="product image" /></li>
                        }
                    </ul>
                    <div class="row">
                        <ul class="the-bullets-dots" data-tesla-plugin="bullets">
@foreach (var itemf in Model.Images)
{
                            <li><div class="col-md-2 col-xs-2"><img src="/images/@itemf.Name" alt="product image" /></div></li>
}
                        </ul>
                    </div>
                    
                </div>
            </div>
            <div class="col-md-6">
                <h2>@Model.FoodName</h2>
                <div class="product-rate">
                    <i class="icon-423" title="full"></i>
                    <i class="icon-423" title="full"></i>
                    <i class="icon-423" title="full"></i>
                    <i class="icon-423" title="full"></i>
                    <i class="icon-421" title="empty"></i>
                </div>
                
                <div class="clear"></div>
                <div class="quantity">
                    <input type="button" value="-" class="minus">
                    <input type="number" step="1" min="1" name="quantity" value="1" title="Qty" class="input-text qty text">
                    <input type="button" value="+" class="plus">
                    <span>10 sold / 12 available</span>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-6">
                        <div class="product-price">PRICE : @Model.FoodPrice AZN</div>
                    </div>
                    <div class="col-md-6">
                        <a href="" class="button-2 addtobucket" name="@Model.ID">Səbətə əlavə et</a>
                      
                    </div>
                </div>
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#description" data-toggle="tab">Description</a></li>
                
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="description">
                        <p>@Model.FoodDescription</p>

                        
                        
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

AdaRestaurants/Views/SiteHome/FoodRestaurant.cshtml
@model IEnumerable<AdaRestaurants.Models.Food>
<script src="~/Content/Zeon/js/jquery-1.10.0.min.js"></script>
@{
    ViewBag.Title = "FoodRestaurant";
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}


<script>
    $(document).ready(function myfunction() {
        $(".addtobucket").click(function myfunction() {
            var id = $(this).attr("name");

            $.ajax({
                type: "GET",
                url: "/SiteHome/AddToBucket",
                data: { id: id },
                success: function myfunction() {
                    $.ajax({
                        type: "GET",
                        url: "/SiteHome/MiniBucketWidget",

                        success: function Verigetir(veri) {
                            $(".cart-all").html('');
                            $(".cart-all").html(veri);
                        }

                    });




                },
                error: function myfunction() {
                    alert("Seçdiyiniz yemək səbətə əlavə olunmadı");
                }
            });
        });
        });
</script>

<div class="box">
    <div class="container">
        <div class="tesla-carousel" data-tesla-plugin="carousel" data-tesla-container=".tesla-carousel-items" data-tesla-item=">div" data-tesla-autoplay="false" data-tesla-rotate="false">
            <div class="site-title">
                <ul class="wrapper-arrows">
                    <li><i class="icon-517 prev" title="left arrow"></i></li>
                    <li><i class="icon-501 next" title="right arrow"></i></li>
                </ul>
                <div class="site-inside"><span>Qidalar</span></div>
            </div>
            <div class="row">
                <div class="tesla-carousel-items">
                    @foreach (var food in Model)
                    {
                        <div class="col-md-3 col-xs-6">
                            <div class="product">
                                <div class="product-cover">
                                    <span class="product-action">

                                    </span>
                                    <div class="product-cover-hover"><span><a href="/SiteHome/FoodDetail/@food.FoodName">Bax</a></span></div>
                                   
                                        <img src="/Images/@food.Images.FirstOrDefault(x=>x.FoodId == food.ID).Name    " alt="product name" />
                                    

                                </div>
                                <div class="product-details">
                                    <h1>
                                        <a href="/SiteHome/FoodDetail/@food.FoodName">
                                            @food.FoodName
                                    </a>
                                </h1>
                                <p>@food.FoodDescription</p>
                                <div class="product-price">
                                    <a name="@food.ID" class="addtobucket">
                                        <i class="icon-257" title="add to cart"></i>
                                    </a>

                                    @food.FoodPrice AZN
                                </div>
                            </div>
                        </div>
                    </div>
                    }


                </div>
            </div>
        </div>
    </div>
</div>


AdaRestaurants/Views/SiteHome/Index.cshtml

@{
    ViewBag.Title = "Ana Sehife";
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}

<h2>Index</h2>

@{

    Html.RenderAction("NewFoods", "SiteHome");
    Html.RenderAction("Brands", "SiteHome");
        Html.RenderAction("Services", "SiteHome");

}

AdaRestaurants/Views/SiteHome/MiniBucketWidget.cshtml
@model AdaRestaurants.App_Classes.Bucket
<script src="~/Content/Zeon/js/jquery-1.10.0.min.js"></script>

<script>

    $(document).ready(function myfunction() {
        $(".deletefood").click(function DeleteFood() {
            var fId = $(this).attr("name");
            $.ajax({
                type: "GET",
                url: "/SiteHome/BucketFoodRemove",
                data: { id: fId },
                success: function myfunction() {
                    $.ajax({
                        type: "GET",
                        url: "/SiteHome/MiniBucketWidget",
                        success: function myfunction(data) {
                            $(".cart-all").html('');
                            $(".cart-all").html(data);

                        }
                    });
                },
                error: function myfunction() {
                    alert("error");
                }
            });
        });
    });
</script>


<div class="cart-all">
    <i class="icon-19" title="19"></i>
    @if (Model != null)
    {
       @Model.SumBucket.ToString("C2");
    }
    else
    {
        <span>0 AZN</span>
    }
    <div class="inside-cart">
        <p>@if (Model != null)
        {
            <span>Səbətdə toplam @Model.Foods.Sum(x => x.Quantity) ədəd məhsul var</span>
        }
        else {
            <span>Səbətdə 0 ədəd məhsul var.</span>
        }</p>
        <ul>

            @if (Model != null)
            {
                foreach (var item in Model.Foods)
                {
                    <li>
                        <div class="inside-cart-image">
                            @if (item.Food.Images != null)
                            {
                                <img src="/Images/@item.Food.Images.FirstOrDefault(x=>x.FoodId == item.Food.ID).Name" alt="product name" />
                            }
                        </div>
                        <a class="deletefood" name="@item.Food.ID">x</a>
                     
                            <a href="/SiteHome/FoodDetail/@item.Food.FoodName">@item.Food.FoodName</a>
                        

                        <p>Toplam: @item.Sum.ToString("C2")</p>
                        <p>Ədəd: @item.Quantity</p>
                    </li>
                }
            }
           
            

        </ul>
    </div>
</div>

AdaRestaurants/Views/SiteHome/NewFoods.cshtml
@model IEnumerable<AdaRestaurants.Models.Food>
<script src="~/Content/Zeon/js/jquery-1.10.0.min.js"></script>


<script>
    $(document).ready(function myfunction() {
        $(".addtobucket").click(function myfunction() {
            var id = $(this).attr("name");
            
            $.ajax({
                type: "GET",
                url: "/SiteHome/AddToBucket",
                data: { id: id },
                success: function myfunction() {
                    $.ajax({
                        type: "GET",
                        url: "/SiteHome/MiniBucketWidget",
                        
                        success: function Verigetir(veri) {
                            $(".cart-all").html('');
                            $(".cart-all").html(veri);
                        }
                        
                    });
                    



                },
                error: function myfunction() {
                    alert("Seçdiyiniz yemək səbətə əlavə olunmadı");
                }
            });
        });
        });
</script>


<div class="box">
    <div class="container">
        <div class="tesla-carousel" data-tesla-plugin="carousel" data-tesla-container=".tesla-carousel-items" data-tesla-item=">div" data-tesla-autoplay="false" data-tesla-rotate="false">
            <div class="site-title">
                <ul class="wrapper-arrows">
                    <li><i class="icon-517 prev" title="left arrow"></i></li>
                    <li><i class="icon-501 next" title="right arrow"></i></li>
                </ul>
                <div class="site-inside"><span>Qidalar</span></div>
            </div>
            <div class="row">
                <div class="tesla-carousel-items">
                    @foreach (var food in Model)
                    {
                        <div class="col-md-3 col-xs-6">
                            <div class="product">
                                <div class="product-cover">
                                    <span class="product-action">
                                        
                                    </span>
                                    <div class="product-cover-hover"><span><a href="/SiteHome/FoodDetail/@food.FoodName">Bax</a></span></div>
                                    @if (food.Images != null)
                                    {
                                        <img src="/Images/@food.Images.FirstOrDefault(x=>x.FoodId == food.ID).Name    " alt="product name" />
                                    }
                                    else
                                    {
                                        <img src="~/Images/Cinnabon.jpg" alt="product name" />
                                    }
                                </div>
                                <div class="product-details">
                                    <h1><a href="/SiteHome/FoodDetail/@food.FoodName">@food.FoodName
                                        </a></h1>
                                    <p>@food.FoodDescription</p>
                                    <div class="product-price"><a name="@food.ID" class="addtobucket">
                                                                   <i class="icon-257" title="add to cart"></i>
                                        </a>
                                       
                                        @food.FoodPrice AZN
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>

AdaRestaurants/Views/SiteHome/Services.cshtml

<div class="box">
    <div class="container">
        <div class="tesla-carousel" data-tesla-plugin="carousel" data-tesla-container=".tesla-carousel-items" data-tesla-item=">div" data-tesla-autoplay="false" data-tesla-rotate="false">
            <div class="site-title">
                <ul class="wrapper-arrows">
                    <li><i class="icon-517 prev" title="left arrow"></i></li>
                    <li><i class="icon-501 next" title="right arrow"></i></li>
                </ul>
                <div class="site-inside">
                    <span>Services</span>
                </div>
            </div>
            <div class="row">
                <div class="tesla-carousel-items">
                    <div class="col-md-4 col-xs-6">
                        <div class="service-1">
                            <h4>Free shipping</h4>
                            <i class="icon-374" title="shipping"></i>
                            <div class="service-description">
                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-6">
                        <div class="service-1 service-color-1">
                            <h4>Return within a month</h4>
                            <i class="icon-271" title="time"></i>
                            <div class="service-description">
                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-6">
                        <div class="service-1 service-color-2">
                            <h4>Cash on delivery</h4>
                            <i class="icon-260" title="cash"></i>
                            <div class="service-description">
                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-6">
                        <div class="service-1">
                            <h4>Free shipping</h4>
                            <i class="icon-374" title="shipping"></i>
                            <div class="service-description">
                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-6">
                        <div class="service-1 service-color-1">
                            <h4>Return within a month</h4>
                            <i class="icon-271" title="time"></i>
                            <div class="service-description">
                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-6">
                        <div class="service-1 service-color-2">
                            <h4>Cash on delivery</h4>
                            <i class="icon-260" title="cash"></i>
                            <div class="service-description">
                                <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AdaRestaurants/Views/SiteHome/Slider.cshtml

<div class="the-slider slider" data-tesla-plugin="slider" data-tesla-item=".slide" data-tesla-next=".slide-right" data-tesla-prev=".slide-left" data-tesla-container=".slide-wrapper">
    <div class="slide-arrows">
        <div class="slide-left"></div>
        <div class="slide-right"></div>
    </div>
    <ul class="slide-wrapper">
        <li class="slide"><img src="/Content/Zeon/images/slider/big-1.jpg" alt="slider image"></li>
        <li class="slide"><img src="/Content/Zeon/images/slider/big-2.jpg" alt="slider image"></li>
        <li class="slide"><img src="/Content/Zeon/images/slider/big-3.jpg" alt="slider image"></li>
    </ul>
    <ul class="the-bullets-dots" data-tesla-plugin="bullets">
        <li><span></span></li>
        <li><span></span></li>
        <li><span></span></li>
    </ul>
</div>